### ISSUE TITLE
Double dots misaligned in text

### ISSUE THREAD

**Issue by emanuel-virca** [SixLabors/ImageSharp.Drawing#123] opened 2021-03-11 11:21 UTC
### Description
When drawing text containing colon (:) the colon is not displayed correctly
![image](https://user-images.githubusercontent.com/8167844/110778808-7faba900-826b-11eb-891f-5c33f6440fea.png)

### Steps to Reproduce

```
private static IImageProcessingContext AddDateStamp(this IImageProcessingContext processingContext, string dateTime, Color color, string fontPath)
{
    Size imgSize = processingContext.GetCurrentSize();

    float defaultFontSize = 18;
    float defaultResolution = 645;
    float defaultPadding = 10;

    float fontSize = imgSize.Width * defaultFontSize / defaultResolution;
    float padding = imgSize.Width * defaultPadding / defaultResolution;
   
    FontCollection collection = new FontCollection();
    FontFamily family = collection.Install(fontPath);
    Font font = family.CreateFont(fontSize, FontStyle.Regular);
   
    FontRectangle fontRectangle = TextMeasurer.Measure(dateTime, new RendererOptions(font));

    var location = new PointF(imgSize.Width - fontRectangle.Width - padding, imgSize.Height - fontRectangle.Height - padding);

    return processingContext.DrawText(dateTime, font, color, location);
}

```

### System Configuration

- ImageSharp.Drawing version: 1.0.0-beta11
- Other ImageSharp packages and versions: ImageSharp 1.0.3
- Environment (Operating system, version and so on): Windows
- .NET Framework version: .NET Core 3.1
- Additional information: The issue happens regardless of what font I am using

**Comment by antonfirsov** [comment] 2021-03-11 15:34
@emanuel-virca using the following app I was unable to reproduce this on my machine:
https://gist.github.com/antonfirsov/077b7c364b422c1665dbe4b7cb2933fb
The app uses `C:\Windows\Fonts\arial.ttf`

- Can you try if it works on your machine?
- Can you provide a similar self-contained repro, including a sample font that doesn't work?

**Comment by JimBobSquarePants** [comment] 2021-03-11 15:48
There's a good chance that @tocsoft fixed this back in January https://github.com/SixLabors/Fonts/pull/159

@emanuel-virca  I'd suggest updating to our latest MyGet build and giving it another go. https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.Fonts/1.0.0-beta13.5.4

**Comment by emanuel-virca** [comment] 2021-03-12 10:19
Many thanks for the quick answers.

After digging more into the issue I found out it actually happens just for Roboto Font. Many apologies for the misleading information provided initially.

I have created a repo for this: [Image Caption Repo](https://github.com/emanuel-virca/image-caption)

@JimBobSquarePants the SixLabors.Fonts (1.0.0-beta0013) is part of the  SixLabors.ImageSharp.Drawing and this is the version I am running now. I have tried installing the SixLabors.Fonts 1.0.0-beta13.5.4 as separate but it was still not working.

**Comment by JimBobSquarePants** [comment] 2021-03-13 02:06
That's a shame, I was hoping the issue was related and we'd already covered it. The issue will be in the fonts library though as that tell this library glyph positions. 

Thanks for creating the repository, that's very useful!

**Comment by JimBobSquarePants** [comment] 2021-03-15 17:09
@emanuel-virca I pilled down your sample and noticed that you are not referencing the Fonts package I specified. 

I added a reference (_also updating Drawing to the latest - unrelated_)

```xml
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.3" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta11.4" />
    <PackageReference Include="SixLabors.Fonts" Version="1.0.0-beta13.5.4" />
  </ItemGroup>
```

And as I hoped the issue had been fixed.

**Before**
![image](https://user-images.githubusercontent.com/385879/111191791-531bc800-85b0-11eb-8a1d-978feef99f58.png)


**After**
![image](https://user-images.githubusercontent.com/385879/111191395-edc7d700-85af-11eb-9233-3a7d210b8d59.png)

I'll close this now as a fix exists.

**Closed by JimBobSquarePants** 2021-03-15 17:09 UTC
Labels: needs triage
