### ISSUE TITLE
ImageProcessingException thrown after attempting to drawing Ascii 32 followed by Ascii 160

### ISSUE THREAD

**Issue by boxofyellow** [SixLabors/ImageSharp.Drawing#92] opened 2020-10-03 12:18 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing **Repro'ed on 1.0.0-beta0010, orginially found on 1.0.0-beta0007**
- [x] I have verified if the problem exists in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I did find done that looks related https://github.com/SixLabors/ImageSharp.Drawing/issues/86, the stacks appear to match, but, but the repro requirements are very different.  Additionally, I don't think this is a missing glyph, the character can be rendered, but only sometimes.

### Description

If you attempt to draw Ascii 32 (space), before drawing Ascii 160 (nonbreaking space) in with a font called "Andale Mono", attempting to render Ascii 160 will throw this exception

```
Unhandled exception. SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
 ---> System.ArgumentOutOfRangeException: Parameter "bufferAlignment" (System.Int32) must be greater than or equal to 0, was -2147483639 (Parameter 'bufferAlignment')
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(String name, String message)
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeGreaterThanOrEqualTo[T](T value, T minimum, String name)
   at SixLabors.ImageSharp.Memory.MemoryGroup`1.Allocate(MemoryAllocator allocator, Int64 totalLength, Int32 bufferAlignment, AllocationOptions options)
   at SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.AllocateGroup[T](MemoryAllocator memoryAllocator, Int64 totalLength, Int32 bufferAlignment, AllocationOptions options)
   at SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.Allocate2D[T](MemoryAllocator memoryAllocator, Int32 width, Int32 height, AllocationOptions options)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.CachingGlyphRenderer.Render(IPath path)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.CachingGlyphRenderer.EndGlyph()
   at SixLabors.Fonts.GlyphInstance.RenderTo(IGlyphRenderer surface, Single pointSize, Vector2 location, Vector2 dpi, Single lineHeight)
   at SixLabors.Fonts.TextRenderer.RenderText(ReadOnlySpan`1 text, RendererOptions options)
   at SixLabors.Fonts.TextRenderer.RenderText(String text, RendererOptions options)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.BeforeImageApply()
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at Magic160.Program.Main(String[] args) in /Users/boxofyellow/test/Magic160/Program.cs:line 31
```

### Steps to Reproduce

Here is an example program that demonstrates this problem.
Magic160.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0010" />
  </ItemGroup>

</Project>
```

Program.cs
```
using System;
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.Drawing.Processing.Processors.Text;
using SixLabors.ImageSharp.PixelFormats;

namespace Magic160
{
    class Program
    {
        static void Main(string[] args)
        {
            const int size = 28;
            foreach (int i in new [] {//160,     // Oddly if you uncomment this line, it will draw all 3 without a problem
                                      (int)' ',  // Generic space, Ascii 32
                                      160})      // Nonbreaking space
            {
                using (var image = new Image<Rgb24>(size, size))
                {
                    var textProcessor = new DrawTextProcessor(
                        new TextGraphicsOptions(),
                        new string((char)i, 1),
                        SystemFonts.CreateFont("Andale Mono", 14.0f),
                        new SolidBrush(Color.White),
                        Pens.Solid(Color.White, 1.0f),
                        new PointF(1, 1));

                    using (var specificProcessor = textProcessor.CreatePixelSpecificProcessor(
                            new Configuration(),
                            image,
                            new Rectangle(1, 1, size, size)))
                    {
                        specificProcessor.Execute();
                    }
                }

                Console.WriteLine($"Drew {i}({(char)i})");
            }
        }
    }
```

### System Configuration

- ImageSharp.Drawing version: **1.0.0-beta0010**
- Other ImageSharp packages and versions:  **N/A**
- Environment (Operating system, version and so on): **macOS Catalina 10.15.7**
- .NET Framework version:
```
~/test/Magic160 > dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.0.101 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- Additional information:
  * I have only observed this problem with the font named "Andale Mono", I have not tried all other fonts, but other common like "Courier New", "Monaco" don't cause the problem.
  * The problem also only appears if you draw Ascii 32 _before_ Ascii 160, if you draw 160 _first_, you can then draw 32, and 160 any number of times without a problem
  * When mentioning drawing in this issue, the characters don't need to be within the same image, the sample program creates a new image for each character.

**Comment by tocsoft** [comment] 2020-10-03 15:29
this will mostly like be because we are failing to deal with characters then end up with a zero width and then we try to create a buffer to render it to.

Not exactly sure off the top of my head why it would work when prefixed but that the zero with should be will be the crux of the problem.

**Comment by tocsoft** [comment] 2020-10-03 19:35
I can't reproduce this one on master but I could on commit beta.10 so it looks like we have already fixed this one.

@boxofyellow you might want to use our [CI releases](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Drawing) (all the same tests are ran for everything in our CI channel so they should be just as stable)  for now.

**Comment by boxofyellow** [comment] 2020-10-04 19:49
@tocsoft Thanks for the quick response, I have a workaround for now that will hold me.  I'll be on the lookout for the next release and switch over once it is out.

**Comment by JimBobSquarePants** [comment] 2021-01-02 21:44
Closing this since beta-11 is out.

**Closed by JimBobSquarePants** 2021-01-02 21:44 UTC
