### ISSUE TITLE
image draw utf-8 text on image

### ISSUE THREAD

**Issue by EngRajabi** [SixLabors/ImageSharp.Drawing#77] opened 2020-08-05 13:56 UTC
Write text in an image when the text is utf8. Broken is shown

**Comment by dlemstra** [comment] 2020-08-05 13:59
We have an issue template. It's there for a reason...

**Comment by tocsoft** [comment] 2020-08-05 13:59
Like I mentioned over at https://github.com/SixLabors/ImageSharp/issues/1306 please actually fill in the template provided when raising the issue.

**Comment by tocsoft** [comment] 2020-08-08 14:59
closing this due to lack of detail... if you can provide the details required from our template feel free to open again but with our template filled in rather than ignored.... ensure you include sample code to reproduce the issue and details of the expected outcome.

**Closed by tocsoft** 2020-08-08 14:59 UTC
Labels: needs triage
